// Code generated by "stringer -type LiteralType -linecomment node.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TNUM-1]
	_ = x[TSTRING-2]
	_ = x[TNIL-3]
}

const _LiteralType_name = "TNUMTSTRINGTNIL"

var _LiteralType_index = [...]uint8{0, 4, 11, 15}

func (i LiteralType) String() string {
	i -= 1
	if i < 0 || i >= LiteralType(len(_LiteralType_index)-1) {
		return "LiteralType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LiteralType_name[_LiteralType_index[i]:_LiteralType_index[i+1]]
}
