// Code generated by "stringer -type Op -linecomment node.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpPLUS-1]
	_ = x[OpMINUS-2]
	_ = x[OpMUL-3]
	_ = x[OpDiv-4]
	_ = x[OpEQ-5]
	_ = x[OpLT-6]
	_ = x[OpGT-7]
	_ = x[OpLEQ-8]
	_ = x[OpGEQ-9]
}

const _Op_name = "OpPLUSOpMINUSOpMULOpDivOpEQOpLTOpGTOpLEQOpGEQ"

var _Op_index = [...]uint8{0, 6, 13, 18, 23, 27, 31, 35, 40, 45}

func (i Op) String() string {
	i -= 1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
